### ISSUE TITLE
Ambiguous expression in example workflow config

### ISSUE THREAD

**Issue by caic99** [platisd/clang-tidy-pr-comments#21]
https://github.com/platisd/clang-tidy-pr-comments/blob/10dea67599cd21bff5391960fe080aa6fd3a164b/README.md?plain=1#L114-L117

Here, the comment says this is "the number of comments per review", but the variable name gives us "suggestions per comment". I suppose the latter one is actually what you mean.

**Comment by platisd** [comment]
Haha, well I see where to confusion can come from.
I think the most accurate is "suggestions per review" actually. 🤣
Github doesn't like when too many suggestions/comments are left at once (ie per review) so we split the necessary comments/suggestions over multiple code reviews.
