### ISSUE TITLE
Posting review comments failed with error code: 403

### ISSUE THREAD

**Issue by caic99** [platisd/clang-tidy-pr-comments#26]
Note: the former steps runs in a container.
https://github.com/deepmodeling/abacus-develop/runs/7535824510?check_suite_focus=true#step:8:1

**Comment by oleg-derevenetz** [comment]
The scheme of using this Action in this repository is incompatible with PR from forks, because `GITHUB_TOKEN` from the fork is used, and not from the base repo, and this token naturally has no permission to create comments in the base repo.

**Comment by platisd** [comment]
> because GITHUB_TOKEN from the fork is used, and not from the base repo, and this token naturally has no permission to create comments in the base repo

Sounds reasonable! :+1: 

Would these [instructions](https://github.com/platisd/clang-tidy-pr-comments#using-this-action-to-safely-perform-analysis-of-pull-requests-from-forks) be of use @caic99 ?

**Comment by oleg-derevenetz** [comment]
> Would these [instructions](https://github.com/platisd/clang-tidy-pr-comments#using-this-action-to-safely-perform-analysis-of-pull-requests-from-forks) be of use @caic99 ?

Yes, that's what this technique is for.

**Comment by caic99** [comment]
@platisd @oleg-derevenetz Thanks for your hint!
