### ISSUE TITLE
A more strict regex extracting diff info is required

### ISSUE THREAD

**Issue by caic99** [platisd/clang-tidy-pr-comments#27]
One of my test failed with an index out of range error (see logs [here](https://github.com/deepmodeling/abacus-develop/runs/7615216499?check_suite_focus=true)).
The patches include changes on something like this:
```text
+    // @@@@@@@
+    // test
+    // @@@@@@@
+    /*
```
And the regex at
https://github.com/platisd/clang-tidy-pr-comments/blob/6f016d02636cd7122e972a64220efd8769f9568a/run_action.py#L135-L137
matches this pattern, not giving out diff info, resulting in error.
I suggest replacing it with a more strict regex match, maybe like `@@ -\d+,\d+ \+\d+,\d+ @@`.

**Comment by caic99** [comment]
To be more accurate, `^@@ -\d+,\d+ \+\d+,\d+ @@$` matches exact the lines which start with and end with "@@". However, adding '$' does not work in my python env for some reason, so adding `^` would be just better.

**Comment by oleg-derevenetz** [comment]
> To be more accurate, ^@@ -\d+,\d+ \+\d+,\d+ @@$ matches exact the lines which start with and end with "@@".

Please note that:

1. The number after the comma may be omitted, and if it is omitted, it defaults to 1. So this one:

```
@@ -1 +1,4 @@
```

is a perfectly valid hunk header.

2. There may be optional section heading after the trailing `@@`, so this one:

```
@@ -1,2 +1,4 @@ void f(int i)
```

is a perfectly valid hunk header as well.

**Comment by platisd** [comment]
Maybe prepare a pull request with this suggestion and we can discuss it further? I am OK with it as long as it doesn't break anything else.
Speaking of it, I probably should start writing some unit tests for this Action... :sweat:
