### ISSUE TITLE
Avoid repeating comments

### ISSUE THREAD

**Issue by platisd** [platisd/clang-tidy-pr-comments#3]
The tool currently does not care whether an identical comment already exists on the same line of code.
Check if there is already a comment before posting a new one.

**Comment by prachipancholi** [comment]
Hey , I would like to contribute, can you elaborate a bit?

**Comment by platisd** [comment]
Hi @prachipancholi, so the current state is that every time the action is run a list of comments will be generated and posted regardless of whether the very same comment has been posted before in the very same line. This can lead to a lot of spam. 

The solve this problem, the idea is that after we have created the list of comments that need to be posted (ie non duplicate comments that are included in the pull request delta) we also need to check if there is another comment with the same content on the same line!
So I think that before posting the comments, we should [fetch the existing pull request review comments](https://docs.github.com/en/rest/reference/pulls#list-review-comments-on-a-pull-request) and if a comment already exists on the same line then we don't post it (e.g. Remove it from the list with the comments to be posted).

Let me know if that helped you understand the problem more.

**Comment by prachipancholi** [comment]
I will try to complete it in 2-3 days. Hope it will work.
