### ISSUE TITLE
Wrong suggestions

### ISSUE THREAD

**Issue by rhaschke** [platisd/clang-tidy-pr-comments#34]
Sometimes I get incorrect suggestions. For example, [for this PR](https://github.com/ubi-agni/moveit_task_constructor/pull/24#discussion_r1013653454) the suggestion is:
```diff
-	auto findIteratorFor = [](const InterfaceState* state, const Interface& interface) {
+	auto findItfind_iterator_forconst InterfaceState* state, const Interface& interface) {
```
instead of the following one, which is correctly produced by `clang-apply-replacements` from the [provided fixes file](https://github.com/ubi-agni/moveit_task_constructor/suites/9124293350/artifacts/423706085):
```diff
-	auto findIteratorFor = [](const InterfaceState* state, const Interface& interface) {
+	auto find_iterator_for = [](const InterfaceState* state, const Interface& interface) {
```

Looks like the replacement is shifted by 6 characters in the suggestion.

**Comment by platisd** [comment]
Also [here](https://github.com/ubi-agni/moveit_task_constructor/pull/24#discussion_r1013653802) apparently. :thinking:

**Comment by oleg-derevenetz** [comment]
Hi all,

The problem here is that the `container.cpp` contains multibyte symbols (for example, at lines 76, 78 and 82). While this Action reads this file in `UTF-8` mode, `clang-tidy` apparently reads it in the `latin-1` mode, hence this problem.

**Comment by oleg-derevenetz** [comment]
@rhaschke Try to use Action URL from #35, namely this URL:

```
uses: oleg-derevenetz/clang-tidy-pr-comments@multibyte-fix
```

This version should work. If it works, then this PR may be merged by @platisd.

**Comment by platisd** [comment]
Nicely done as always @oleg-derevenetz 👌
@rhaschke could you please confirm if `oleg-derevenetz/clang-tidy-pr-comments@multibyte-fix` fixes your issue?

**Comment by rhaschke** [comment]
Thanks to both of you for this super-fast fix!
