### ISSUE TITLE
1.3.0 Seems to break warning without suggested replacement

### ISSUE THREAD

**Issue by Summon528** [platisd/clang-tidy-pr-comments#39]
Just noticed my actions are failing with the following message, my guess is that it breaks when there are no suggested replacements. I will try to make a minimal example if you need it.
```
Traceback (most recent call last):
  File "/action/run_action.py", line 4[12], in <module>
    sys.exit(main())
  File "/action/run_action.py", line 268, in main
    suggestion_end = suggestion_begin + diagnostic["ReplacementLength"]
KeyError: 'ReplacementLength'
```

**Comment by platisd** [comment]
Crap, will take a look. In the meanwhile, please use `1.2.0` if possible.

Thanks for reporting it. If you have a link to the failed job that would be great.

**Comment by Summon528** [comment]
Repro here:
https://github.com/Summon528/-clang-tidy-pr-comments-39/pull/1

**Comment by platisd** [comment]
Should work now as of `1.3.1`, please feel free to re-open the issue if you still face the same problem.
