### ISSUE TITLE
Approve PR when issues have been fixed

### ISSUE THREAD

**Issue by rdb** [platisd/clang-tidy-pr-comments#44]
Thanks for making this action!

It's working well in the sense that it's requesting changes when clang-tidy has issues, but even once those issues have been fixed by the submitter, it will forever remain in a "changes requested" state, preventing merging of the PR without administrator override.

This could be fixed by simply having the action submit an "approved" review when there are no changes to make, or otherwise, dismissing its previous review.

**Comment by platisd** [comment]
I see you point however I also see an problem with the reasoning. Submitting an approval implies "the code is good to be merged" which cannot be inferred by the absence of clang-tidy warnings.
The tool may be able to tell you when there's something wrong with the code as far as `clang-tidy` has a say, but not much more than that. This is why most, if not all, Github actions and CI pipelines I've come across, block merging when they fail and allow it when they succeed, but they don't approve anything themselves.

**Comment by platisd** [comment]
Reading again, I think I understand the actual problem though: The Action should take dismiss its old request for changes if it has ran without issues.

I can look into that.

**Comment by rdb** [comment]
Anyone can approve a PR so I don't think an approval of any one particular user can in any case be taken as an indication the PR is good to be merged in general - but I would be quite happy with simply dismissing the old request for changes (assuming those review comments no longer apply), I think that would also solve the problem.

Thanks!

**Comment by platisd** [comment]
I am thinking of the current flow: If the bot has no comments to make, it will go through any reviews and will try to find its own where it has requested changes and will dismiss them.

I hope the bot has enough permissions to do that, we'll see.
Btw, I wonder if selecting the "dismiss" option as seen below in the branch protection rules, also dismisses the change requests:
![image](https://user-images.githubusercontent.com/7327776/218427627-1f3f68a2-1e6f-4076-b3f8-4d959c2d4e66.png)

**Comment by platisd** [comment]
@rdb you can try out the `dismiss_stale_reviews` branch and see if it's what you're after.
I tried it out myself [here](https://github.com/platisd/cpp-command-parser/pull/21).

![image](https://user-images.githubusercontent.com/7327776/218443943-12c8233c-498f-420a-9ac0-385e7dd1700d.png)

**Comment by rdb** [comment]
I'm trying, though I'm running into a different problem right now:
```
fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
```
Not sure why, it worked before.

**Comment by platisd** [comment]
:thinking: the issue seems very irrelevant, do you have some link so I can take a look?

**Comment by rdb** [comment]
Yeah, sure:
https://github.com/rdb/panda3d/blob/master/.github/workflows/lint.yml
https://github.com/rdb/panda3d/actions/runs/4163065036/jobs/7202990629

It worked before.  Not sure what changed.

**Comment by rdb** [comment]
My bad, I think I had accidentally removed the fetch-depth line.

**Comment by rdb** [comment]
It's working great.  Dismissing all the previous reviews once there are no more warnings.  Thank you!

**Comment by platisd** [comment]
Thanks for suggesting this new feature! :+1:
