### ISSUE TITLE
Should "fixed" review requests get dismissed

### ISSUE THREAD

**Issue by renefritze** [platisd/clang-tidy-pr-comments#72]
I've noticed that when I fix a tidy issue the associated change request is not dismissed.

I've set up an MWE [here](https://github.com/renefritze/tidy_comments_test/pull/5)
where I first add a commit that introduces an issue and a second commit that doesn't have tidy complain.

Since no fixes files is now created, it looks like the action [skips out early](https://github.com/renefritze/tidy_comments_test/actions/runs/7753138708/job/21143894454#step:8:74)

Is that expected behavior, a potential bug? Did I [misconfigure](https://github.com/renefritze/tidy_comments_test/blob/main/.github/workflows/ci.yml#L30) the action maybe?

Note I'm not using the clang-tidy-diff script because I'm currently limited to clang >= 17 in my real application and it's just not currently distributed with the python wrapper I'm using.

**Comment by platisd** [comment]
> Could not find the clang-tidy fixes file 'clang-tidy-result/fixes.yml'. Perhaps it wasn't created?

I am not sure what's the "correct" behavior here. Shouldn't an empty `fixes.yml` be generated even if there are no warnings?

**Comment by renefritze** [comment]
At least the tidy version that I am using does not generate an empty file if it did not find anything to fix. 
After [making sure there is an empty file](https://github.com/renefritze/tidy_comments_test/pull/5/commits/8200232f01c8701828fe9726a49155d4cf888410) to run on, the review indeed gets dismissed as I would have expected

**Comment by platisd** [comment]
Interesting. Well, there are two ways forward:
1. Leave things as they are and make it the user's responsibility to create that file if it doesn't exist. This comes with the risk of frustrating users that are potentially on some newer `clang-tidy` versions. :thinking: 
2. Treat a missing file as an empty file and make the experience seamless to all users. This comes with the risk of missing to report any typos or wrong paths of the fixes YAML file. :tired_face: 

Thinking loudly here:

We could consider (2) if we find a way to make it really obvious that the fixes file was missing. I suspect that a printout "the file is missing and we assume there were no errors" in the logs may not be enough. Perhaps posting something in the PR as a comment instead? Which of course may in turn result to spamming... :sweat:

**Comment by oleg-derevenetz** [comment]
> This comes with the risk of missing to report any typos or wrong paths of the fixes YAML file.

Issues of this kind should become obvious at early stages of `clang-tidy-pr-comments` setup during the first real health test, and if everything worked once, then in the future everything should work too (until someone makes some changes that also need to be tested).

> Perhaps posting something in the PR as a comment instead? Which of course may in turn result to spamming...

I'm also against posting comments like "everything is OK", because they add no value.
