### ISSUE TITLE
Clang tidy action failing to post comments.

### ISSUE THREAD

**Issue by VarunNagaraju** [platisd/clang-tidy-pr-comments#75]
The clang-tidy-pr-comments action is failing to post comment with the following assert 

```
Processing 'cppcoreguidelines-pro-type-member-init' at lines 340-340 of libbinlogevents/include/compression/payload_event_buffer_istream.h...
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/_actions/platisd/clang-tidy-pr-comments/v1/run_action.py", line 623, in main
    post_review_comments(
  File "/home/runner/work/_actions/platisd/clang-tidy-pr-comments/v1/run_action.py", line 433, in post_review_comments
    assert result.status_code in (
           ^^^^^^^^^^^^^^^^^^^^^^^
```
The workflow file can be found at https://github.com/percona/percona-server/blob/testing/.github/workflows/main.yml.
The workflow is configured with the following permissions.
```
permissions:
      issues: write
      pull-requests: write
```
Also, pull request ID is being passed through properly

```
Run ${GITHUB_ACTION_PATH}/action_launcher.bash
  ${GITHUB_ACTION_PATH}/action_launcher.bash
  shell: /usr/bin/bash -l {0}
  env:
    UBUNTU_CODE_NAME: jammy
    COMPILER_VERSION: 17
    BOOST_VERSION: 1_77_0
    BOOST_DIR: /home/runner/my_boost
    INPUT_GITHUB_TOKEN: ***
    INPUT_CLANG_TIDY_FIXES: clang-tidy-result/fixes.yml
    INPUT_PULL_REQUEST_ID: 5241
    INPUT_REQUEST_CHANGES: true
    INPUT_SUGGESTIONS_PER_COMMENT: 10
    INPUT_REPO_PATH_PREFIX: /home/runner/work
```

For more info, check out https://github.com/percona/percona-server/pull/5241

**Comment by oleg-derevenetz** [comment]
Hi @VarunNagaraju your workflow will not work with PRs from forks, and https://github.com/percona/percona-server/pull/5241 is a cross-fork PR. This workflow is executed with credentials that do not allow to modify the pull requests in the base repo.

**Comment by VarunNagaraju** [comment]
@oleg-derevenetz Thanks for the quick response. I'll try with the artifact method for forks.

**Comment by VarunNagaraju** [comment]
Hi @oleg-derevenetz , I see that in order to use on : workflow_run trigger, the workflow files should be on the master/default branch. If that's the case, how would one test if the workflows are working correctly without modifying the default branch?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
https://github.com/percona/percona-server/pull/5242

**Comment by oleg-derevenetz** [comment]
Hi @VarunNagaraju yes, it requires the workflow(s) to be on the default branch. In order to test this, you'll need two forks. You should make PR from one fork to another (which should already have corresponding workflows in its default branch).

**Comment by VarunNagaraju** [comment]
Thanks for the assistance @oleg-derevenetz !
