### ISSUE TITLE
Release 1.5.0 is not marked as latest

### ISSUE THREAD

**Issue by oleg-derevenetz** [platisd/clang-tidy-pr-comments#81]
Is there any reason for this? Or did you just forget to check the box? :)

![release](https://github.com/user-attachments/assets/6c74a000-1b31-432b-b512-fc01c8ebb419)

**Comment by platisd** [comment]
Certainly an omission on my side, will fix

**Comment by platisd** [comment]
![image](https://github.com/user-attachments/assets/ffb7ffd7-1351-4668-8d09-211306701803)

For whatever reason not all of them show up there, but anyway
