### ISSUE TITLE
Add option to use existing Python installation

### ISSUE THREAD

**Issue by psalz** [platisd/clang-tidy-pr-comments#84]
Due to [this unresolved issue](https://github.com/actions/setup-python/issues/871) with the `setup-python` action I'm currently unable to use this action on our self-hosted runners. Since we already have Python 3.12 pre-installed on the runners however, it would be great if there was an option to skip the installation step and simply use the existing installation instead!

Edit: Or maybe even better a `python-path` option, that if set, skips the `setup-python` action and uses it to create the `venv` (i.e. something like `"${{ steps.setup-python.outputs.python-path || inputs.python_path }}" -m venv "${GITHUB_ACTION_PATH}/venv"`)

**Comment by platisd** [comment]
I can take a look but don't have a good way of testing it. Sounds like you have a good solution to the issue though?
Feel free to provide a PR that addresses this in the meanwhile.
