### ISSUE TITLE
Disable diagnostic errors?

### ISSUE THREAD

**Issue by blozano-tt** [platisd/clang-tidy-pr-comments#86]
Despite the fact that I have only one check enabled. Our repo gets a lot of comments about clang diagnostic errors.

https://github.com/tenstorrent/tt-metal/pull/14624/files#r1826880450

Not all of the code in our project is x86 host code, and so it struggles to find headers when those files are changed.

People don’t generally check in code with errors. Is there a way to block diagnostic errors from becoming comments?

**Comment by blozano-tt** [comment]
Maybe I can filter the fixes.yaml file..

**Comment by platisd** [comment]
Do you also get those warnings when you run clang-tidy locally via the command line?

**Comment by blozano-tt** [comment]
> Do you also get those warnings when you run clang-tidy locally via the command line?

I assume it would, but I haven't verified.

**Comment by oleg-derevenetz** [comment]
> People don’t generally check in code with errors. Is there a way to block diagnostic errors from becoming comments?

For instance, you can alter the mutual dependencies of your workflows in such a way that Clang-Tidy diagnostics run only if the code in PR generally compiles. In other words, run the build workflow first, and run the Clang-Tidy workflow only if the build workflow succeeds.

**Comment by blozano-tt** [comment]
I believe I made the issue much better with the following commit:

https://github.com/tenstorrent/tt-metal/commit/0b39880650e4907fa61ffc44e06b51aa96bf7419

compile_commands.json was missing information about test case source files.

However, I worry that I'll still have problems when changes are made to files that are not a part of the main build.

**Comment by blozano-tt** [comment]
Closing since this is probably something that should be handled by the user.
