### ISSUE TITLE
`jq` is a dependency, but may not be present in all environments

### ISSUE THREAD

**Issue by nsmithtt** [platisd/clang-tidy-pr-comments#88]
`jq` seems to be used in `action_launcher.bash` [here](https://github.com/platisd/clang-tidy-pr-comments/blob/88780c4ca5471b97de8f228219d1e39b1a472142/action_launcher.bash#L6).

I'm using this action on a private runner that doesn't have `jq` installed by default, I run into this issue:
```
Run "${GITHUB_ACTION_PATH}/action_launcher.bash"
/__w/_actions/platisd/clang-tidy-pr-comments/v1.6.0/action_launcher.bash: line 6: jq: command not found
```

**Comment by platisd** [comment]
What kind of runner are you using it with?

**Comment by nsmithtt** [comment]
It's actually just ubuntu-latest but with a custom docker.  We can probably just add `jq` to our docker, I just figure it's a bit cleaner to keep the dependency self contained.

**Comment by platisd** [comment]
Can you please try out `platisd/clang-tidy-pr-comments@install_jq` and let me know if it works with your setup?

Relevant PR #89

**Comment by oleg-derevenetz** [comment]
First of all, we can just throw the `jq` away and use a command-line argument (or an environment variable) set through the `action.yml` (via the `${{ github.event.issue.number || github.event.number }}` construction I suppose). This should be tested of course.

**Comment by oleg-derevenetz** [comment]
Here is an alternative approach without `jq`: #90

**Comment by oleg-derevenetz** [comment]
Hope this works :) I would be grateful for feedback from @nsmithtt.

**Comment by platisd** [comment]
I am rather confident that since our tests went through, it should work :grin:

**Comment by nsmithtt** [comment]
I should probably test on a faster pipeline, it takes ~30 min for my pipeline to build / clang-tidy everything.

@platisd, failing because of a transitive dep now :)
```
 /__w/_actions/dcarbone/install-jq-action/v2.1.0/scripts/unixish-17.sh: line 76: curl: command not found
```

@oleg-derevenetz I'll test yours next, will comment back here in a couple hours, have to step away for a bit.

**Comment by platisd** [comment]
> @platisd, failing because of a transitive dep now :)

Well then, I trust the merged one will not have this issue. :}

**Comment by oleg-derevenetz** [comment]
> failing because of a transitive dep now :)

That's why I don't like 3-rd party actions depending on other 3-rd party actions :)

**Comment by nsmithtt** [comment]
Thank you both, @oleg-derevenetz pretty confident yours will work

@platisd I think the merged one hopefully does work, since it doesn't use `install-jq-action`.
